# The main entry point of your workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.


configfile: "config/config.yaml"


pepfile: config["pepfile"]


report: "report/workflow.rst"


# Allow users to fix the underlying OS via singularity.
container: "docker://continuumio/miniconda3"


include: "rules/common.smk"
include: "rules/extract-data.smk"
include: "rules/process-data.smk"
include: "rules/post-processing.smk"


# The first rule should define the default target files
# Subsequent target rules can be specified below. They should start with all_*.
rule all:
    input:
        expand("results/{id}/personal-data-summary.tsv", id=get_all_ids()),
        expand("results/{id}/moved", id=get_all_ids()),
        expand("results/{id}/plots/summary-for-{id}.svg", id=get_all_ids())
